Server
std::string Server::serverName
Referenced by Server, startServer, listOnlinePlayers.
volatile bool Server::running
Referenced by Server, startServer, stopServer, restartServer, sendCommand, listOnlinePlayers.
std::string Server::serverPath
Referenced by Server, backupServer, listOnlinePlayers.
std::string Server::serverJarName
Referenced by Server, backupServer, listOnlinePlayers.
std::string Server::serverAccount
Referenced by Server, listOnlinePlayers.
int Server::maxHeapAlloc
Referenced by Server, listOnlinePlayers.
int Server::minHeapAlloc
Referenced by Server, listOnlinePlayers.
int Server::gcThreadCount
Referenced by Server, listOnlinePlayers.
std::string Server::backupPath
Referenced by Server, backupServer.
std::vector<std::string> Server::worldsToBackup
Referenced by Server, backupServer.
std::vector<std::string> Server::javaArgs
Referenced by Server, listOnlinePlayers.
std::vector<std::string> Server::serverOptions
Referenced by Server, listOnlinePlayers.
Connection* Server::connection
Referenced by startServer, stopServer, sendCommand.
log4cpp::Category* Server::log
Referenced by Server, ~Server, updateServer, backupServer, startServer, stopServer, serverStatus, restartServer, sendCommand, listOnlinePlayers.
struct event_base* Server::event_base
Referenced by Server, startServer.
Server::Server(std::string serverName, std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::string backupPath, std::vector< std::string > worldsToBackup, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions, struct event_base *base)
References running, serverName, serverPath, serverJarName, serverAccount, maxHeapAlloc, minHeapAlloc, gcThreadCount, backupPath, worldsToBackup, javaArgs, serverOptions, event_base, log.
Server::~Server()
References log.
void Server::updateServer()
References log.
void Server::backupServer()
References log, sendCommand, worldsToBackup, serverPath, backupPath, serverJarName.
void Server::backupServer(std::string backupPath)
References log, sendCommand, worldsToBackup, serverPath, backupPath, serverJarName.
void Server::serverStatus()
References log.
void Server::startServer()
References log, running, serverName, event_base, connection.
Referenced by restartServer.
void Server::stopServer()
References log, running, connection.
Referenced by restartServer.
void Server::restartServer()
References log, running, stopServer, startServer.
void Server::listOnlinePlayers()
References log.
void Server::listOnlinePlayers(std::string playerName)
References serverPath, serverJarName, serverAccount, maxHeapAlloc, minHeapAlloc, gcThreadCount, javaArgs, serverOptions, log, running, sendCommand, serverName.
void Server::sendCommand(std::string command)
References log, running, connection.
Referenced by backupServer, listOnlinePlayers.
void Server::updateServer(std::string serverPath, std::string serverJarName, std::string serverAccount)
References log.
void Server::backupServer(std::string serverPath, std::string serverAccount, std::string backupPath, std::vector< std::string > worldsToBackup)
References log.