MinecraftServerService::Server
PIPE_OPS
typedef Server&(* MinecraftServerService::Server::ServerManipulator) (Server &))(Server &)
typedef std::basic_ostream<char, std::char_traits<char> > MinecraftServerService::Server::CoutType
typedef CoutType&(* MinecraftServerService::Server::StandardEndLine) (CoutType &))(CoutType &)
std::string MinecraftServerService::Server::serverName
int MinecraftServerService::Server::serverPID
Referenced by MinecraftServerService::BukkitServer::startServer, MinecraftServerService::BungeeCordServer::startServer, MinecraftServerService::GenericServer::startServer, MinecraftServerService::SpigotServer::startServer, MinecraftServerService::VanillaServer::startServer.
int MinecraftServerService::Server::childProcessUID
int MinecraftServerService::Server::childProcessGID
int MinecraftServerService::Server::childProcessStdin[2][2]
int MinecraftServerService::Server::childProcessStdout[2][2]
Referenced by MinecraftServerService::BukkitServer::startServer, MinecraftServerService::BungeeCordServer::startServer, MinecraftServerService::GenericServer::startServer, MinecraftServerService::SpigotServer::startServer, MinecraftServerService::VanillaServer::startServer.
log4cpp::Category* MinecraftServerService::Server::log
Referenced by MinecraftServerService::BukkitServer::BukkitServer, MinecraftServerService::BukkitServer::~BukkitServer, MinecraftServerService::BukkitServer::updateServer, MinecraftServerService::BukkitServer::backupServer, MinecraftServerService::BukkitServer::startServer, MinecraftServerService::BukkitServer::stopServer, MinecraftServerService::BukkitServer::serverStatus, MinecraftServerService::BukkitServer::restartServer, MinecraftServerService::BukkitServer::sendCommand, MinecraftServerService::BukkitServer::listOnlinePlayers, MinecraftServerService::BungeeCordServer::BungeeCordServer, MinecraftServerService::BungeeCordServer::~BungeeCordServer, MinecraftServerService::BungeeCordServer::updateServer, MinecraftServerService::BungeeCordServer::backupServer, MinecraftServerService::BungeeCordServer::startServer, MinecraftServerService::BungeeCordServer::stopServer, MinecraftServerService::BungeeCordServer::serverStatus, MinecraftServerService::BungeeCordServer::restartServer, MinecraftServerService::BungeeCordServer::sendCommand, MinecraftServerService::BungeeCordServer::listOnlinePlayers, MinecraftServerService::GenericServer::GenericServer, MinecraftServerService::GenericServer::~GenericServer, MinecraftServerService::GenericServer::updateServer, MinecraftServerService::GenericServer::backupServer, MinecraftServerService::GenericServer::startServer, MinecraftServerService::GenericServer::stopServer, MinecraftServerService::GenericServer::serverStatus, MinecraftServerService::GenericServer::restartServer, MinecraftServerService::GenericServer::sendCommand, outputListenerThread, MinecraftServerService::SpigotServer::SpigotServer, MinecraftServerService::SpigotServer::~SpigotServer, MinecraftServerService::SpigotServer::updateServer, MinecraftServerService::SpigotServer::backupServer, MinecraftServerService::SpigotServer::startServer, MinecraftServerService::SpigotServer::stopServer, MinecraftServerService::SpigotServer::serverStatus, MinecraftServerService::SpigotServer::restartServer, MinecraftServerService::SpigotServer::sendCommand, MinecraftServerService::SpigotServer::listOnlinePlayers, MinecraftServerService::VanillaServer::VanillaServer, MinecraftServerService::VanillaServer::~VanillaServer, MinecraftServerService::VanillaServer::updateServer, MinecraftServerService::VanillaServer::backupServer, MinecraftServerService::VanillaServer::startServer, MinecraftServerService::VanillaServer::stopServer, MinecraftServerService::VanillaServer::serverStatus, MinecraftServerService::VanillaServer::restartServer, MinecraftServerService::VanillaServer::sendCommand, MinecraftServerService::VanillaServer::listOnlinePlayers.
struct event_base* MinecraftServerService::Server::base
Referenced by MinecraftServerService::BukkitServer::startServer, MinecraftServerService::BungeeCordServer::startServer, MinecraftServerService::GenericServer::startServer, outputListenerThread, MinecraftServerService::SpigotServer::startServer, MinecraftServerService::VanillaServer::startServer.
std::vector<Listener*>* MinecraftServerService::Server::listeners
Referenced by MinecraftServerService::BukkitServer::startServer, MinecraftServerService::BukkitServer::listOnlinePlayers, MinecraftServerService::BungeeCordServer::startServer, MinecraftServerService::BungeeCordServer::listOnlinePlayers, MinecraftServerService::GenericServer::startServer, MinecraftServerService::SpigotServer::startServer, MinecraftServerService::SpigotServer::listOnlinePlayers, MinecraftServerService::VanillaServer::startServer, MinecraftServerService::VanillaServer::listOnlinePlayers.
virtual void MinecraftServerService::Server::updateServer()=0
virtual void MinecraftServerService::Server::backupServer()=0
virtual void MinecraftServerService::Server::backupServer(std::string backupPath)=0
virtual void MinecraftServerService::Server::serverStatus()=0
virtual void MinecraftServerService::Server::startServer()=0
virtual void MinecraftServerService::Server::stopServer()=0
virtual void MinecraftServerService::Server::restartServer()=0
virtual void MinecraftServerService::Server::reloadServer()=0
virtual std::string MinecraftServerService::Server::listOnlinePlayers()=0
virtual bool MinecraftServerService::Server::listOnlinePlayers(std::string playerName)=0
virtual void MinecraftServerService::Server::sendCommand(std::string command)=0
bool MinecraftServerService::Server::isRunning()
Referenced by MinecraftServerService::BukkitServer::startServer, MinecraftServerService::BukkitServer::stopServer, MinecraftServerService::BukkitServer::restartServer, MinecraftServerService::BukkitServer::sendCommand, MinecraftServerService::BungeeCordServer::startServer, MinecraftServerService::BungeeCordServer::stopServer, MinecraftServerService::BungeeCordServer::restartServer, MinecraftServerService::BungeeCordServer::sendCommand, MinecraftServerService::GenericServer::startServer, MinecraftServerService::GenericServer::stopServer, MinecraftServerService::GenericServer::restartServer, MinecraftServerService::GenericServer::sendCommand, MinecraftServerService::SpigotServer::startServer, MinecraftServerService::SpigotServer::stopServer, MinecraftServerService::SpigotServer::restartServer, MinecraftServerService::SpigotServer::sendCommand, MinecraftServerService::VanillaServer::startServer, MinecraftServerService::VanillaServer::stopServer, MinecraftServerService::VanillaServer::restartServer, MinecraftServerService::VanillaServer::sendCommand.
Server& MinecraftServerService::Server::operator<<(const T &x)
References PIPE_WRITE.
Server& MinecraftServerService::Server::operator<<(const std::string &x)
References PIPE_WRITE.
std::istream& MinecraftServerService::Server::operator>>(std::istream &in)
References PIPE_WRITE.
Server& MinecraftServerService::Server::operator<<(StandardEndLine manip)
References PIPE_WRITE.
void MinecraftServerService::Server::outputListenerThread(int serverPID, int childProcessStdout, struct event_base *base, log4cpp::Category *log, std::vector< Listener * > *listeners)
References base, log, serverOutputEvent.
Referenced by MinecraftServerService::BukkitServer::startServer, MinecraftServerService::BungeeCordServer::startServer, MinecraftServerService::GenericServer::startServer, launchServerProcess, MinecraftServerService::SpigotServer::startServer, MinecraftServerService::VanillaServer::startServer.
void MinecraftServerService::Server::serverOutputEvent(evutil_socket_t fd, short event, void *arg)
References len.
Referenced by outputListenerThread, launchServerProcess.
void MinecraftServerService::Server::getUIDAndGIDFromUsername(const char *user)
Referenced by launchServerProcess.
void MinecraftServerService::Server::launchServerProcess(std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions)
References getUIDAndGIDFromUsername, PIPE_READ, PIPE_WRITE, outputListenerThread, serverOutputEvent.
Referenced by MinecraftServerService::BukkitServer::startServer, MinecraftServerService::BungeeCordServer::startServer, MinecraftServerService::GenericServer::startServer, MinecraftServerService::SpigotServer::startServer, MinecraftServerService::VanillaServer::startServer.