MinecraftServerService::ServerStream
ServerProcessBuf* MinecraftServerService::ServerStream::serverProcess
Referenced by ServerStream, ~ServerStream, stopServer, sendCommand, rdbuf.
log4cpp::Category* MinecraftServerService::ServerStream::log
Referenced by ServerStream, ~ServerStream, stopServer, sendCommand.
std::string MinecraftServerService::ServerStream::serverName
Referenced by ServerStream, sendCommand.
MinecraftServerService::ServerStream::ServerStream(std::string _serverName, std::string _serverPath, std::string _serverJarName, std::string _serverAccount, int _maxHeapAlloc, int _minHeapAlloc, int _gcThreadCount, std::vector< std::string > _javaArgs, std::vector< std::string > _serverOptions)
References serverName, log, serverProcess.
MinecraftServerService::ServerStream::~ServerStream()
References log, stopServer, serverProcess.
ServerProcessBuf * MinecraftServerService::ServerStream::rdbuf()
References serverProcess.
Referenced by MinecraftServerService::Server::startServer, MinecraftServerService::Server::stopServer, MinecraftServerService::Server::restartServer, MinecraftServerService::Server::sendCommand, MinecraftServerService::Server::logger.
void MinecraftServerService::ServerStream::stopServer()
References log, serverProcess, MinecraftServerService::ServerProcessBuf::exited, sendCommand.
Referenced by ~ServerStream.
void MinecraftServerService::ServerStream::sendCommand(std::string command)
References log, serverProcess, MinecraftServerService::ServerProcessBuf::exited, serverName.
Referenced by stopServer.