MinecraftServerService::ServerProcessBuf
PIPE_OPS
typedef std::streambuf::traits_type MinecraftServerService::ServerProcessBuf::traits_type
@1
char MinecraftServerService::ServerProcessBuf::outbuf_[bufsize][bufsize]
Referenced by ServerProcessBuf, sync.
char MinecraftServerService::ServerProcessBuf::inbuf_[bufsize+16-sizeof(int)][bufsize+16-sizeof(int)]
Referenced by ServerProcessBuf.
log4cpp::Category* MinecraftServerService::ServerProcessBuf::log
Referenced by ServerProcessBuf.
char MinecraftServerService::ServerProcessBuf::currentCharacter
int MinecraftServerService::ServerProcessBuf::server
int MinecraftServerService::ServerProcessBuf::childProcessUID
int MinecraftServerService::ServerProcessBuf::childProcessGID
int MinecraftServerService::ServerProcessBuf::childProcessStdin[2][2]
Referenced by ~ServerProcessBuf, sync.
int MinecraftServerService::ServerProcessBuf::childProcessStdout[2][2]
Referenced by ~ServerProcessBuf, underflow.
MinecraftServerService::ServerProcessBuf::ServerProcessBuf(std::string serverName, std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions)
References log, inbuf_, outbuf_, bufsize, startServer.
MinecraftServerService::ServerProcessBuf::~ServerProcessBuf()
References stopServer, childProcessStdin, PIPE_WRITE, childProcessStdout, PIPE_READ.
bool MinecraftServerService::ServerProcessBuf::exited()
ServerProcessBuf::int_type MinecraftServerService::ServerProcessBuf::overflow(int c)
References sync.
int MinecraftServerService::ServerProcessBuf::underflow()
References childProcessStdout, PIPE_READ, bufsize.
int MinecraftServerService::ServerProcessBuf::sync()
References childProcessStdin, PIPE_WRITE, outbuf_.
Referenced by overflow.
void MinecraftServerService::ServerProcessBuf::startServer(std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions)
Referenced by ServerProcessBuf.
void MinecraftServerService::ServerProcessBuf::launchServerProcess(std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions)
void MinecraftServerService::ServerProcessBuf::getUIDAndGIDFromUsername(const char *user)
void MinecraftServerService::ServerProcessBuf::stopServer()
Referenced by ~ServerProcessBuf.
MinecraftServerService::ServerProcessBuf::ServerProcessBuf(const ServerProcessBuf &)
ServerProcessBuf& MinecraftServerService::ServerProcessBuf::operator=(const ServerProcessBuf &)