MinecraftServerService::GenericServer
std::string MinecraftServerService::GenericServer::serverName
Referenced by GenericServer.
std::string MinecraftServerService::GenericServer::serverPath
Referenced by GenericServer, backupServer, startServer.
std::string MinecraftServerService::GenericServer::serverJarName
Referenced by GenericServer, backupServer, startServer.
std::string MinecraftServerService::GenericServer::serverAccount
Referenced by GenericServer, startServer.
int MinecraftServerService::GenericServer::maxHeapAlloc
Referenced by GenericServer, startServer.
int MinecraftServerService::GenericServer::minHeapAlloc
Referenced by GenericServer, startServer.
int MinecraftServerService::GenericServer::gcThreadCount
Referenced by GenericServer, startServer.
std::string MinecraftServerService::GenericServer::backupPath
Referenced by GenericServer, backupServer.
std::vector<std::string> MinecraftServerService::GenericServer::worldsToBackup
Referenced by GenericServer, backupServer.
std::vector<std::string> MinecraftServerService::GenericServer::javaArgs
Referenced by GenericServer, startServer.
std::vector<std::string> MinecraftServerService::GenericServer::serverOptions
Referenced by GenericServer, startServer.
MinecraftServerService::GenericServer::GenericServer(std::string serverName, std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::string backupPath, std::vector< std::string > worldsToBackup, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions)
References serverPath, serverJarName, serverAccount, maxHeapAlloc, minHeapAlloc, gcThreadCount, backupPath, worldsToBackup, javaArgs, serverOptions, MinecraftServerService::Server::log, serverName.
MinecraftServerService::GenericServer::~GenericServer()
References MinecraftServerService::Server::log.
void MinecraftServerService::GenericServer::updateServer()
References MinecraftServerService::Server::log.
void MinecraftServerService::GenericServer::backupServer()
References MinecraftServerService::Server::log, worldsToBackup, serverPath, backupPath, serverJarName.
void MinecraftServerService::GenericServer::backupServer(std::string backupPath)
References MinecraftServerService::Server::log, worldsToBackup, serverPath, backupPath, serverJarName.
void MinecraftServerService::GenericServer::serverStatus()
References MinecraftServerService::Server::log.
void MinecraftServerService::GenericServer::startServer()
References MinecraftServerService::Server::log, MinecraftServerService::Server::isRunning, serverPath, MinecraftServerService::Server::launchServerProcess, serverJarName, serverAccount, maxHeapAlloc, minHeapAlloc, gcThreadCount, javaArgs, serverOptions, MinecraftServerService::Server::outputListenerThread, MinecraftServerService::Server::serverPID, MinecraftServerService::Server::childProcessStdout, MinecraftServerService::Server::PIPE_READ, MinecraftServerService::Server::base, MinecraftServerService::Server::listeners.
Referenced by restartServer.
void MinecraftServerService::GenericServer::stopServer()
References MinecraftServerService::Server::log, MinecraftServerService::Server::isRunning.
Referenced by restartServer.
void MinecraftServerService::GenericServer::restartServer()
References MinecraftServerService::Server::log, MinecraftServerService::Server::isRunning, stopServer, startServer.
void MinecraftServerService::GenericServer::reloadServer()
std::string MinecraftServerService::GenericServer::listOnlinePlayers()
bool MinecraftServerService::GenericServer::listOnlinePlayers(std::string playerName)
References sendCommand.
void MinecraftServerService::GenericServer::sendCommand(std::string command)
References MinecraftServerService::Server::log, MinecraftServerService::Server::isRunning.
Referenced by listOnlinePlayers.
void MinecraftServerService::GenericServer::logger(size_t linesRequested, std::stringstream *output, log4cpp::Category *log)