MinecraftServerService::VanillaServer
std::string MinecraftServerService::VanillaServer::serverName
Referenced by VanillaServer.
std::string MinecraftServerService::VanillaServer::serverPath
Referenced by VanillaServer, backupServer, startServer.
std::string MinecraftServerService::VanillaServer::serverJarName
Referenced by VanillaServer, backupServer, startServer.
std::string MinecraftServerService::VanillaServer::serverAccount
Referenced by VanillaServer, startServer.
int MinecraftServerService::VanillaServer::maxHeapAlloc
Referenced by VanillaServer, startServer.
int MinecraftServerService::VanillaServer::minHeapAlloc
Referenced by VanillaServer, startServer.
int MinecraftServerService::VanillaServer::gcThreadCount
Referenced by VanillaServer, startServer.
std::string MinecraftServerService::VanillaServer::backupPath
Referenced by VanillaServer, backupServer.
std::vector<std::string> MinecraftServerService::VanillaServer::worldsToBackup
Referenced by VanillaServer, backupServer.
std::vector<std::string> MinecraftServerService::VanillaServer::javaArgs
Referenced by VanillaServer, startServer.
std::vector<std::string> MinecraftServerService::VanillaServer::serverOptions
Referenced by VanillaServer, startServer.
MinecraftServerService::VanillaServer::VanillaServer(std::string serverName, std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::string backupPath, std::vector< std::string > worldsToBackup, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions)
References serverPath, serverJarName, serverAccount, maxHeapAlloc, minHeapAlloc, gcThreadCount, backupPath, worldsToBackup, javaArgs, serverOptions, MinecraftServerService::Server::log, serverName.
MinecraftServerService::VanillaServer::~VanillaServer()
References MinecraftServerService::Server::log.
void MinecraftServerService::VanillaServer::updateServer()
References MinecraftServerService::Server::log.
void MinecraftServerService::VanillaServer::backupServer()
References MinecraftServerService::Server::log, worldsToBackup, serverPath, backupPath, serverJarName.
void MinecraftServerService::VanillaServer::backupServer(std::string backupPath)
References MinecraftServerService::Server::log, worldsToBackup, serverPath, backupPath, serverJarName.
void MinecraftServerService::VanillaServer::serverStatus()
References MinecraftServerService::Server::log.
void MinecraftServerService::VanillaServer::startServer()
References MinecraftServerService::Server::log, MinecraftServerService::Server::isRunning, serverPath, MinecraftServerService::Server::launchServerProcess, serverJarName, serverAccount, maxHeapAlloc, minHeapAlloc, gcThreadCount, javaArgs, serverOptions, MinecraftServerService::Server::outputListenerThread, MinecraftServerService::Server::serverPID, MinecraftServerService::Server::childProcessStdout, MinecraftServerService::Server::PIPE_READ, MinecraftServerService::Server::base, MinecraftServerService::Server::listeners.
Referenced by restartServer.
void MinecraftServerService::VanillaServer::stopServer()
References MinecraftServerService::Server::log, MinecraftServerService::Server::isRunning.
Referenced by restartServer.
void MinecraftServerService::VanillaServer::restartServer()
References MinecraftServerService::Server::log, MinecraftServerService::Server::isRunning, stopServer, startServer.
void MinecraftServerService::VanillaServer::reloadServer()
References listOnlinePlayers, sendCommand.
std::string MinecraftServerService::VanillaServer::listOnlinePlayers()
References MinecraftServerService::Server::log, MinecraftServerService::Server::listeners.
Referenced by reloadServer.
bool MinecraftServerService::VanillaServer::listOnlinePlayers(std::string playerName)
References MinecraftServerService::Server::log, MinecraftServerService::Server::listeners.
void MinecraftServerService::VanillaServer::sendCommand(std::string command)
References MinecraftServerService::Server::log, MinecraftServerService::Server::isRunning.
Referenced by reloadServer.
void MinecraftServerService::VanillaServer::logger(size_t linesRequested, std::stringstream *output, log4cpp::Category *log)