client.cpp
int controlSocket
Referenced by writeToSocket, readFromSocket, main, createSocket, recieveCommand.
int rc
Referenced by readFromSocket, recieveCommand.
int len
Referenced by main, createSocket, Json::throwLogicError, Json::containsControlCharacter0, Json::valueToString, MinecraftServerService::Server::serverOutputEvent.
char buff[4][4]
Referenced by readFromSocket, recieveCommand.
void help(char *argv0)
Referenced by main.
void writeToSocket(std::string command)
References controlSocket.
Referenced by main.
std::string readFromSocket()
References rc, controlSocket, buff.
Referenced by main.
int main(int argc, char *argv[])
References controlSocket, len, writeToSocket, readFromSocket, help.