mainLoop.cpp
void sigint_handler(int sig)
Referenced by main.
void mainLoop(std::vector< MinecraftServerService::Server * > *servers, log4cpp::Category &root, int controlSocket, struct event_base *base)
References cb_data::servers, recieveCommand.
Referenced by main.
void writeToSocket(std::string message, int controlSocket, log4cpp::Category &root)
Referenced by recieveCommand.
std::string readFromSocket(int controlSocket, log4cpp::Category &root)
References rc, buff.
void recieveCommand(int _controlSocket, short what, void *arg)
References controlSocket, cb_data::servers, cb_data::root, rc, writeToSocket, buff.
Referenced by mainLoop.