.TH "/home/mel/projects/Misc/Minecraft Server Service/src/bukkitServer.h" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mel/projects/Misc/Minecraft Server Service/src/bukkitServer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'server\&.h'\fP
.br
\fC#include 'log4cpp/Category\&.hh'\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMinecraftServerService::BukkitServer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMinecraftServerService\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
