.TH "cb_data" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cb_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBMinecraftServerService::Server\fP * > * \fBservers\fP"
.br
.ti -1c
.RI "log4cpp::Category & \fBroot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file mainLoop\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "log4cpp::Category& cb_data::root"

.PP
Definition at line 47 of file mainLoop\&.cpp\&.
.SS "std::vector<\fBMinecraftServerService::Server\fP*>* cb_data::servers"

.PP
Definition at line 46 of file mainLoop\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
