.TH "/home/mel/projects/Misc/Minecraft Server Service/src/createSocket.cpp" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mel/projects/Misc/Minecraft Server Service/src/createSocket.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'createSocket\&.h'\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/un\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'log4cpp/Category\&.hh'\fP
.br
\fC#include <event2/event\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcreateSocket\fP (log4cpp::Category &root)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int createSocket (log4cpp::Category & root)"

.PP
Definition at line 33 of file createSocket\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
