.TH "Json::OurReader::ErrorInfo" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::OurReader::ErrorInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBToken\fP \fBtoken_\fP"
.br
.ti -1c
.RI "std::string \fBmessage_\fP"
.br
.ti -1c
.RI "\fBLocation\fP \fBextra_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1158 of file jsoncpp\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLocation\fP Json::OurReader::ErrorInfo::extra_"

.PP
Definition at line 1162 of file jsoncpp\&.cpp\&.
.SS "std::string Json::OurReader::ErrorInfo::message_"

.PP
Definition at line 1161 of file jsoncpp\&.cpp\&.
.SS "\fBToken\fP Json::OurReader::ErrorInfo::token_"

.PP
Definition at line 1160 of file jsoncpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
