.TH "Json::OurFeatures" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::OurFeatures \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBOurFeatures\fP \fBall\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBallowComments_\fP"
.br
.ti -1c
.RI "bool \fBstrictRoot_\fP"
.br
.ti -1c
.RI "bool \fBallowDroppedNullPlaceholders_\fP"
.br
.ti -1c
.RI "bool \fBallowNumericKeys_\fP"
.br
.ti -1c
.RI "bool \fBallowSingleQuotes_\fP"
.br
.ti -1c
.RI "bool \fBfailIfExtra_\fP"
.br
.ti -1c
.RI "bool \fBrejectDupKeys_\fP"
.br
.ti -1c
.RI "bool \fBallowSpecialFloats_\fP"
.br
.ti -1c
.RI "int \fBstackLimit_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1083 of file jsoncpp\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBOurFeatures\fP Json::OurFeatures::all ()\fC [static]\fP"

.PP
Definition at line 1100 of file jsoncpp\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Json::OurFeatures::allowComments_"

.PP
Definition at line 1086 of file jsoncpp\&.cpp\&.
.SS "bool Json::OurFeatures::allowDroppedNullPlaceholders_"

.PP
Definition at line 1088 of file jsoncpp\&.cpp\&.
.SS "bool Json::OurFeatures::allowNumericKeys_"

.PP
Definition at line 1089 of file jsoncpp\&.cpp\&.
.SS "bool Json::OurFeatures::allowSingleQuotes_"

.PP
Definition at line 1090 of file jsoncpp\&.cpp\&.
.SS "bool Json::OurFeatures::allowSpecialFloats_"

.PP
Definition at line 1093 of file jsoncpp\&.cpp\&.
.SS "bool Json::OurFeatures::failIfExtra_"

.PP
Definition at line 1091 of file jsoncpp\&.cpp\&.
.SS "bool Json::OurFeatures::rejectDupKeys_"

.PP
Definition at line 1092 of file jsoncpp\&.cpp\&.
.SS "int Json::OurFeatures::stackLimit_"

.PP
Definition at line 1094 of file jsoncpp\&.cpp\&.
.SS "bool Json::OurFeatures::strictRoot_"

.PP
Definition at line 1087 of file jsoncpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
