.TH "Json::BuiltStyledStreamWriter" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::BuiltStyledStreamWriter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits StreamWriter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuiltStyledStreamWriter\fP (std::string const &indentation, \fBCommentStyle::Enum\fP cs, std::string const &colonSymbol, std::string const &nullSymbol, std::string const &endingLineFeedSymbol, bool useSpecialFloats, unsigned int precision)"
.br
.ti -1c
.RI "int \fBwrite\fP (Value const &root, std::ostream *sout) override"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef std::vector< std::string > \fBChildValues\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBwriteValue\fP (Value const &value)"
.br
.ti -1c
.RI "void \fBwriteArrayValue\fP (Value const &value)"
.br
.ti -1c
.RI "bool \fBisMultineArray\fP (Value const &value)"
.br
.ti -1c
.RI "void \fBpushValue\fP (std::string const &value)"
.br
.ti -1c
.RI "void \fBwriteIndent\fP ()"
.br
.ti -1c
.RI "void \fBwriteWithIndent\fP (std::string const &value)"
.br
.ti -1c
.RI "void \fBindent\fP ()"
.br
.ti -1c
.RI "void \fBunindent\fP ()"
.br
.ti -1c
.RI "void \fBwriteCommentBeforeValue\fP (Value const &root)"
.br
.ti -1c
.RI "void \fBwriteCommentAfterValueOnSameLine\fP (Value const &root)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBhasCommentForValue\fP (const Value &value)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBChildValues\fP \fBchildValues_\fP"
.br
.ti -1c
.RI "std::string \fBindentString_\fP"
.br
.ti -1c
.RI "unsigned int \fBrightMargin_\fP"
.br
.ti -1c
.RI "std::string \fBindentation_\fP"
.br
.ti -1c
.RI "\fBCommentStyle::Enum\fP \fBcs_\fP"
.br
.ti -1c
.RI "std::string \fBcolonSymbol_\fP"
.br
.ti -1c
.RI "std::string \fBnullSymbol_\fP"
.br
.ti -1c
.RI "std::string \fBendingLineFeedSymbol_\fP"
.br
.ti -1c
.RI "bool \fBaddChildValues_\fP: 1"
.br
.ti -1c
.RI "bool \fBindented_\fP: 1"
.br
.ti -1c
.RI "bool \fBuseSpecialFloats_\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBprecision_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4810 of file jsoncpp\&.cpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::vector<std::string> \fBJson::BuiltStyledStreamWriter::ChildValues\fP\fC [private]\fP"

.PP
Definition at line 4834 of file jsoncpp\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Json::BuiltStyledStreamWriter::BuiltStyledStreamWriter (std::string const & indentation, \fBCommentStyle::Enum\fP cs, std::string const & colonSymbol, std::string const & nullSymbol, std::string const & endingLineFeedSymbol, bool useSpecialFloats, unsigned int precision)"

.PP
Definition at line 4849 of file jsoncpp\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Json::BuiltStyledStreamWriter::hasCommentForValue (const Value & value)\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 5080 of file jsoncpp\&.cpp\&.
.SS "void Json::BuiltStyledStreamWriter::indent ()\fC [private]\fP"

.PP
Definition at line 5042 of file jsoncpp\&.cpp\&.
.SS "bool Json::BuiltStyledStreamWriter::isMultineArray (Value const & value)\fC [private]\fP"

.PP
Definition at line 4990 of file jsoncpp\&.cpp\&.
.SS "void Json::BuiltStyledStreamWriter::pushValue (std::string const & value)\fC [private]\fP"

.PP
Definition at line 5017 of file jsoncpp\&.cpp\&.
.SS "void Json::BuiltStyledStreamWriter::unindent ()\fC [private]\fP"

.PP
Definition at line 5044 of file jsoncpp\&.cpp\&.
.SS "int Json::BuiltStyledStreamWriter::write (Value const & root, std::ostream * sout)\fC [override]\fP"

.PP
Definition at line 4869 of file jsoncpp\&.cpp\&.
.SS "void Json::BuiltStyledStreamWriter::writeArrayValue (Value const & value)\fC [private]\fP"

.PP
Definition at line 4943 of file jsoncpp\&.cpp\&.
.SS "void Json::BuiltStyledStreamWriter::writeCommentAfterValueOnSameLine (Value const & root)\fC [private]\fP"

.PP
Definition at line 5068 of file jsoncpp\&.cpp\&.
.SS "void Json::BuiltStyledStreamWriter::writeCommentBeforeValue (Value const & root)\fC [private]\fP"

.PP
Definition at line 5049 of file jsoncpp\&.cpp\&.
.SS "void Json::BuiltStyledStreamWriter::writeIndent ()\fC [private]\fP"

.PP
Definition at line 5024 of file jsoncpp\&.cpp\&.
.SS "void Json::BuiltStyledStreamWriter::writeValue (Value const & value)\fC [private]\fP"

.PP
Definition at line 4884 of file jsoncpp\&.cpp\&.
.SS "void Json::BuiltStyledStreamWriter::writeWithIndent (std::string const & value)\fC [private]\fP"

.PP
Definition at line 5036 of file jsoncpp\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Json::BuiltStyledStreamWriter::addChildValues_\fC [private]\fP"

.PP
Definition at line 4844 of file jsoncpp\&.cpp\&.
.SS "\fBChildValues\fP Json::BuiltStyledStreamWriter::childValues_\fC [private]\fP"

.PP
Definition at line 4836 of file jsoncpp\&.cpp\&.
.SS "std::string Json::BuiltStyledStreamWriter::colonSymbol_\fC [private]\fP"

.PP
Definition at line 4841 of file jsoncpp\&.cpp\&.
.SS "\fBCommentStyle::Enum\fP Json::BuiltStyledStreamWriter::cs_\fC [private]\fP"

.PP
Definition at line 4840 of file jsoncpp\&.cpp\&.
.SS "std::string Json::BuiltStyledStreamWriter::endingLineFeedSymbol_\fC [private]\fP"

.PP
Definition at line 4843 of file jsoncpp\&.cpp\&.
.SS "std::string Json::BuiltStyledStreamWriter::indentation_\fC [private]\fP"

.PP
Definition at line 4839 of file jsoncpp\&.cpp\&.
.SS "bool Json::BuiltStyledStreamWriter::indented_\fC [private]\fP"

.PP
Definition at line 4845 of file jsoncpp\&.cpp\&.
.SS "std::string Json::BuiltStyledStreamWriter::indentString_\fC [private]\fP"

.PP
Definition at line 4837 of file jsoncpp\&.cpp\&.
.SS "std::string Json::BuiltStyledStreamWriter::nullSymbol_\fC [private]\fP"

.PP
Definition at line 4842 of file jsoncpp\&.cpp\&.
.SS "unsigned int Json::BuiltStyledStreamWriter::precision_\fC [private]\fP"

.PP
Definition at line 4847 of file jsoncpp\&.cpp\&.
.SS "unsigned int Json::BuiltStyledStreamWriter::rightMargin_\fC [private]\fP"

.PP
Definition at line 4838 of file jsoncpp\&.cpp\&.
.SS "bool Json::BuiltStyledStreamWriter::useSpecialFloats_\fC [private]\fP"

.PP
Definition at line 4846 of file jsoncpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
