.TH "Json::OurReader::Token" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::OurReader::Token \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTokenType\fP \fBtype_\fP"
.br
.ti -1c
.RI "\fBLocation\fP \fBstart_\fP"
.br
.ti -1c
.RI "\fBLocation\fP \fBend_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1151 of file jsoncpp\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLocation\fP Json::OurReader::Token::end_"

.PP
Definition at line 1155 of file jsoncpp\&.cpp\&.
.SS "\fBLocation\fP Json::OurReader::Token::start_"

.PP
Definition at line 1154 of file jsoncpp\&.cpp\&.
.SS "\fBTokenType\fP Json::OurReader::Token::type_"

.PP
Definition at line 1153 of file jsoncpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
