.TH "Json::OurCharReader" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::OurCharReader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits CharReader\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOurCharReader\fP (bool collectComments, \fBOurFeatures\fP const &features)"
.br
.ti -1c
.RI "bool \fBparse\fP (char const *beginDoc, char const *endDoc, Value *root, std::string *errs) override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool const \fBcollectComments_\fP"
.br
.ti -1c
.RI "\fBOurReader\fP \fBreader_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2084 of file jsoncpp\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Json::OurCharReader::OurCharReader (bool collectComments, \fBOurFeatures\fP const & features)\fC [inline]\fP"

.PP
Definition at line 2088 of file jsoncpp\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Json::OurCharReader::parse (char const * beginDoc, char const * endDoc, Value * root, std::string * errs)\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 2094 of file jsoncpp\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool const Json::OurCharReader::collectComments_\fC [private]\fP"

.PP
Definition at line 2085 of file jsoncpp\&.cpp\&.
.SS "\fBOurReader\fP Json::OurCharReader::reader_\fC [private]\fP"

.PP
Definition at line 2086 of file jsoncpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
