.TH "Json::OurReader::StructuredError" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::OurReader::StructuredError \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ptrdiff_t \fBoffset_start\fP"
.br
.ti -1c
.RI "ptrdiff_t \fBoffset_limit\fP"
.br
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1110 of file jsoncpp\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string Json::OurReader::StructuredError::message"

.PP
Definition at line 1113 of file jsoncpp\&.cpp\&.
.SS "ptrdiff_t Json::OurReader::StructuredError::offset_limit"

.PP
Definition at line 1112 of file jsoncpp\&.cpp\&.
.SS "ptrdiff_t Json::OurReader::StructuredError::offset_start"

.PP
Definition at line 1111 of file jsoncpp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
