.TH "/home/mel/projects/Misc/Minecraft Server Service/src/mainLoop.cpp" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mel/projects/Misc/Minecraft Server Service/src/mainLoop.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'server\&.h'\fP
.br
\fC#include 'parser\&.h'\fP
.br
\fC#include 'mainLoop\&.h'\fP
.br
\fC#include 'setupServers\&.h'\fP
.br
\fC#include <json/json\&.h>\fP
.br
\fC#include 'log4cpp/Category\&.hh'\fP
.br
\fC#include <string>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/un\&.h>\fP
.br
\fC#include <event2/event\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcb_data\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsigint_handler\fP (int sig)"
.br
.ti -1c
.RI "void \fBmainLoop\fP (std::vector< \fBMinecraftServerService::Server\fP * > *servers, log4cpp::Category &root, int \fBcontrolSocket\fP, struct event_base *base)"
.br
.ti -1c
.RI "void \fBwriteToSocket\fP (std::string message, int \fBcontrolSocket\fP, log4cpp::Category &root)"
.br
.ti -1c
.RI "std::string \fBreadFromSocket\fP (int \fBcontrolSocket\fP, log4cpp::Category &root)"
.br
.ti -1c
.RI "void \fBrecieveCommand\fP (int _controlSocket, short what, void *arg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mainLoop (std::vector< \fBMinecraftServerService::Server\fP * > * servers, log4cpp::Category & root, int controlSocket, struct event_base * base)"

.PP
Definition at line 49 of file mainLoop\&.cpp\&.
.SS "std::string readFromSocket (int controlSocket, log4cpp::Category & root)"

.PP
Definition at line 66 of file mainLoop\&.cpp\&.
.SS "void recieveCommand (int _controlSocket, short what, void * arg)"

.PP
Definition at line 77 of file mainLoop\&.cpp\&.
.SS "void sigint_handler (int sig)"

.PP
Definition at line 38 of file mainLoop\&.cpp\&.
.SS "void writeToSocket (std::string message, int controlSocket, log4cpp::Category & root)"

.PP
Definition at line 59 of file mainLoop\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
