.TH "/home/mel/projects/Misc/Minecraft Server Service/src/mainLoop.h" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mel/projects/Misc/Minecraft Server Service/src/mainLoop.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'log4cpp/Category\&.hh'\fP
.br
\fC#include <event2/event\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsigint_handler\fP (int sig)"
.br
.ti -1c
.RI "void \fBmainLoop\fP (std::vector< \fBMinecraftServerService::Server\fP * > *servers, log4cpp::Category &root, evutil_socket_t \fBcontrolSocket\fP, struct event_base *base)"
.br
.ti -1c
.RI "void \fBwriteToSocket\fP (std::string message, int \fBcontrolSocket\fP, log4cpp::Category &root)"
.br
.ti -1c
.RI "std::string \fBreadFromSocket\fP (int \fBcontrolSocket\fP, log4cpp::Category &root)"
.br
.ti -1c
.RI "void \fBrecieveCommand\fP (int \fBcontrolSocket\fP, short what, void *arg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mainLoop (std::vector< \fBMinecraftServerService::Server\fP * > * servers, log4cpp::Category & root, evutil_socket_t controlSocket, struct event_base * base)"

.SS "std::string readFromSocket (int controlSocket, log4cpp::Category & root)"

.PP
Definition at line 66 of file mainLoop\&.cpp\&.
.SS "void recieveCommand (int controlSocket, short what, void * arg)"

.PP
Definition at line 77 of file mainLoop\&.cpp\&.
.SS "void sigint_handler (int sig)"

.PP
Definition at line 38 of file mainLoop\&.cpp\&.
.SS "void writeToSocket (std::string message, int controlSocket, log4cpp::Category & root)"

.PP
Definition at line 59 of file mainLoop\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
