.TH "MinecraftServerService" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBukkitServer\fP"
.br
.ti -1c
.RI "class \fBBungeeCordServer\fP"
.br
.ti -1c
.RI "class \fBGenericServer\fP"
.br
.ti -1c
.RI "class \fBServer\fP"
.br
.ti -1c
.RI "class \fBSpigotServer\fP"
.br
.ti -1c
.RI "class \fBVanillaServer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
