.TH "MinecraftServerService::cb_data" 3 "Thu Jun 2 2016" "Version 0.7.4" "Minecraft Server Service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService::cb_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBServer\fP * > * \fBservers\fP"
.br
.ti -1c
.RI "log4cpp::Category & \fBroot\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "log4cpp::Category& MinecraftServerService::cb_data::root"

.SS "std::vector<\fBServer\fP*>* MinecraftServerService::cb_data::servers"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Service from the source code\&.
