.TH "MinecraftServerService::Server::token_t" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService::Server::token_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uintptr_t \fBptr\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file server\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uintptr_t MinecraftServerService::Server::token_t::ptr"

.PP
Definition at line 84 of file server\&.h\&.
.SS "int MinecraftServerService::Server::token_t::size"

.PP
Definition at line 85 of file server\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
