.TH "MinecraftServerService::Listener" 3 "Thu Jun 2 2016" "Version 0.7.4" "Minecraft Server Service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService::Listener \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <listener\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBListener\fP (int _lines)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlines\fP = 0"
.br
.ti -1c
.RI "std::stringstream \fBoutput\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MinecraftServerService::Listener::Listener (int _lines)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int MinecraftServerService::Listener::lines = 0"

.SS "std::stringstream MinecraftServerService::Listener::output"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Service from the source code\&.
