.TH "MinecraftServerService::BungeeCordServer" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService::BungeeCordServer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bungeecordServer\&.h>\fP
.PP
Inherits \fBMinecraftServerService::Server\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBungeeCordServer\fP (std::string \fBserverName\fP, std::string \fBserverPath\fP, std::string \fBserverJarName\fP, std::string \fBserverAccount\fP, int \fBmaxHeapAlloc\fP, int \fBminHeapAlloc\fP, int \fBgcThreadCount\fP, std::string \fBbackupPath\fP, std::vector< std::string > \fBjavaArgs\fP, std::vector< std::string > \fBserverOptions\fP)"
.br
.ti -1c
.RI "virtual \fB~BungeeCordServer\fP ()"
.br
.ti -1c
.RI "void \fBupdateServer\fP ()"
.br
.ti -1c
.RI "void \fBbackupServer\fP ()"
.br
.ti -1c
.RI "void \fBbackupServer\fP (std::string \fBbackupPath\fP)"
.br
.ti -1c
.RI "void \fBserverStatus\fP ()"
.br
.ti -1c
.RI "void \fBstartServer\fP ()"
.br
.ti -1c
.RI "void \fBstopServer\fP ()"
.br
.ti -1c
.RI "void \fBrestartServer\fP ()"
.br
.ti -1c
.RI "void \fBreloadServer\fP ()"
.br
.ti -1c
.RI "std::string \fBlistOnlinePlayers\fP ()"
.br
.ti -1c
.RI "bool \fBlistOnlinePlayers\fP (std::string playerName)"
.br
.ti -1c
.RI "void \fBsendCommand\fP (std::string command)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBserverName\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBlogger\fP (size_t linesRequested, std::stringstream *output, log4cpp::Category *\fBlog\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBserverPath\fP"
.br
.ti -1c
.RI "std::string \fBserverJarName\fP"
.br
.ti -1c
.RI "std::string \fBserverAccount\fP"
.br
.ti -1c
.RI "int \fBmaxHeapAlloc\fP"
.br
.ti -1c
.RI "int \fBminHeapAlloc\fP"
.br
.ti -1c
.RI "int \fBgcThreadCount\fP"
.br
.ti -1c
.RI "std::string \fBbackupPath\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBworldsToBackup\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBjavaArgs\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBserverOptions\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 33 of file bungeecordServer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MinecraftServerService::BungeeCordServer::BungeeCordServer (std::string serverName, std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::string backupPath, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions)"

.PP
Definition at line 33 of file bungeecordServer\&.cpp\&.
.SS "MinecraftServerService::BungeeCordServer::~BungeeCordServer ()\fC [virtual]\fP"

.PP
Definition at line 43 of file bungeecordServer\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void MinecraftServerService::BungeeCordServer::backupServer ()\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 51 of file bungeecordServer\&.cpp\&.
.SS "void MinecraftServerService::BungeeCordServer::backupServer (std::string backupPath)\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 82 of file bungeecordServer\&.cpp\&.
.SS "std::string MinecraftServerService::BungeeCordServer::listOnlinePlayers ()\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 158 of file bungeecordServer\&.cpp\&.
.SS "bool MinecraftServerService::BungeeCordServer::listOnlinePlayers (std::string playerName)\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 182 of file bungeecordServer\&.cpp\&.
.SS "void MinecraftServerService::BungeeCordServer::logger (size_t linesRequested, std::stringstream * output, log4cpp::Category * log)\fC [protected]\fP"

.SS "void MinecraftServerService::BungeeCordServer::reloadServer ()\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 104 of file bungeecordServer\&.cpp\&.
.SS "void MinecraftServerService::BungeeCordServer::restartServer ()\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 138 of file bungeecordServer\&.cpp\&.
.SS "void MinecraftServerService::BungeeCordServer::sendCommand (std::string command)\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 148 of file bungeecordServer\&.cpp\&.
.SS "void MinecraftServerService::BungeeCordServer::serverStatus ()\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 134 of file bungeecordServer\&.cpp\&.
.SS "void MinecraftServerService::BungeeCordServer::startServer ()\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 108 of file bungeecordServer\&.cpp\&.
.SS "void MinecraftServerService::BungeeCordServer::stopServer ()\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 120 of file bungeecordServer\&.cpp\&.
.SS "void MinecraftServerService::BungeeCordServer::updateServer ()\fC [virtual]\fP"

.PP
Implements \fBMinecraftServerService::Server\fP\&.
.PP
Definition at line 47 of file bungeecordServer\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string MinecraftServerService::BungeeCordServer::backupPath\fC [protected]\fP"

.PP
Definition at line 68 of file bungeecordServer\&.h\&.
.SS "int MinecraftServerService::BungeeCordServer::gcThreadCount\fC [protected]\fP"

.PP
Definition at line 67 of file bungeecordServer\&.h\&.
.SS "std::vector<std::string> MinecraftServerService::BungeeCordServer::javaArgs\fC [protected]\fP"

.PP
Definition at line 70 of file bungeecordServer\&.h\&.
.SS "int MinecraftServerService::BungeeCordServer::maxHeapAlloc\fC [protected]\fP"

.PP
Definition at line 65 of file bungeecordServer\&.h\&.
.SS "int MinecraftServerService::BungeeCordServer::minHeapAlloc\fC [protected]\fP"

.PP
Definition at line 66 of file bungeecordServer\&.h\&.
.SS "std::string MinecraftServerService::BungeeCordServer::serverAccount\fC [protected]\fP"

.PP
Definition at line 64 of file bungeecordServer\&.h\&.
.SS "std::string MinecraftServerService::BungeeCordServer::serverJarName\fC [protected]\fP"

.PP
Definition at line 63 of file bungeecordServer\&.h\&.
.SS "std::string MinecraftServerService::BungeeCordServer::serverName"

.PP
Definition at line 58 of file bungeecordServer\&.h\&.
.SS "std::vector<std::string> MinecraftServerService::BungeeCordServer::serverOptions\fC [protected]\fP"

.PP
Definition at line 71 of file bungeecordServer\&.h\&.
.SS "std::string MinecraftServerService::BungeeCordServer::serverPath\fC [protected]\fP"

.PP
Definition at line 62 of file bungeecordServer\&.h\&.
.SS "std::vector<std::string> MinecraftServerService::BungeeCordServer::worldsToBackup\fC [protected]\fP"

.PP
Definition at line 69 of file bungeecordServer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
