.TH "MinecraftServerService::Parser" 3 "Thu Jun 2 2016" "Version 0.7.4" "Minecraft Server Service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService::Parser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Json::Value \fBparse\fP (std::string configFile)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBgetFileContents\fP (const char *filename)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::string MinecraftServerService::Parser::getFileContents (const char * filename)\fC [protected]\fP"

.SS "Json::Value MinecraftServerService::Parser::parse (std::string configFile)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Service from the source code\&.
