.TH "MinecraftServerService::Server" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService::Server \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.PP
Inherited by \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::BungeeCordServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, and \fBMinecraftServerService::VanillaServer\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBListener\fP"
.br
.ti -1c
.RI "struct \fBServerOutputEventData\fP"
.br
.ti -1c
.RI "struct \fBtoken_t\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPIPE_OPS\fP { \fBPIPE_READ\fP = 0, \fBPIPE_WRITE\fP = 1 }"
.br
.ti -1c
.RI "typedef \fBServer\fP &(* \fBServerManipulator\fP) (\fBServer\fP &)"
.br
.ti -1c
.RI "typedef std::basic_ostream< char, std::char_traits< char > > \fBCoutType\fP"
.br
.ti -1c
.RI "typedef \fBCoutType\fP &(* \fBStandardEndLine\fP) (\fBCoutType\fP &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBupdateServer\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBbackupServer\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBbackupServer\fP (std::string backupPath)=0"
.br
.ti -1c
.RI "virtual void \fBserverStatus\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBstartServer\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBstopServer\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBrestartServer\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBreloadServer\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBlistOnlinePlayers\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBlistOnlinePlayers\fP (std::string playerName)=0"
.br
.ti -1c
.RI "virtual void \fBsendCommand\fP (std::string command)=0"
.br
.ti -1c
.RI "bool \fBisRunning\fP ()"
.br
.ti -1c
.RI "template<typename T > \fBServer\fP & \fBoperator<<\fP (const T &x)"
.br
.ti -1c
.RI "\fBServer\fP & \fBoperator<<\fP (const std::string &x)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in)"
.br
.ti -1c
.RI "\fBServer\fP & \fBoperator<<\fP (\fBStandardEndLine\fP manip)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBserverName\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBgetUIDAndGIDFromUsername\fP (const char *user)"
.br
.ti -1c
.RI "void \fBlaunchServerProcess\fP (std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBoutputListenerThread\fP (int \fBserverPID\fP, int \fBchildProcessStdout\fP, struct event_base *\fBbase\fP, log4cpp::Category *\fBlog\fP, std::vector< \fBListener\fP * > *\fBlisteners\fP)"
.br
.ti -1c
.RI "static void \fBserverOutputEvent\fP (evutil_socket_t fd, short event, void *arg)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBserverPID\fP = \-1"
.br
.ti -1c
.RI "int \fBchildProcessUID\fP"
.br
.ti -1c
.RI "int \fBchildProcessGID\fP"
.br
.ti -1c
.RI "int \fBchildProcessStdin\fP [2]"
.br
.ti -1c
.RI "int \fBchildProcessStdout\fP [2]"
.br
.ti -1c
.RI "log4cpp::Category * \fBlog\fP"
.br
.ti -1c
.RI "struct event_base * \fBbase\fP = event_base_new()"
.br
.ti -1c
.RI "std::vector< \fBListener\fP * > * \fBlisteners\fP = new std::vector<\fBListener\fP*>"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file server\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::basic_ostream<char, std::char_traits<char> > \fBMinecraftServerService::Server::CoutType\fP"

.PP
Definition at line 88 of file server\&.h\&.
.SS "typedef \fBServer\fP&(* MinecraftServerService::Server::ServerManipulator) (\fBServer\fP &)"

.PP
Definition at line 87 of file server\&.h\&.
.SS "typedef \fBCoutType\fP&(* MinecraftServerService::Server::StandardEndLine) (\fBCoutType\fP &)"

.PP
Definition at line 89 of file server\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMinecraftServerService::Server::PIPE_OPS\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPIPE_READ \fP\fP
.TP
\fB\fIPIPE_WRITE \fP\fP
.PP
Definition at line 63 of file server\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void MinecraftServerService::Server::backupServer ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "virtual void MinecraftServerService::Server::backupServer (std::string backupPath)\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "void MinecraftServerService::Server::getUIDAndGIDFromUsername (const char * user)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 245 of file server\&.h\&.
.SS "bool MinecraftServerService::Server::isRunning ()\fC [inline]\fP"

.PP
Definition at line 118 of file server\&.h\&.
.SS "void MinecraftServerService::Server::launchServerProcess (std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 258 of file server\&.h\&.
.SS "virtual std::string MinecraftServerService::Server::listOnlinePlayers ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "virtual bool MinecraftServerService::Server::listOnlinePlayers (std::string playerName)\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "template<typename T > \fBServer\fP& MinecraftServerService::Server::operator<< (const T & x)\fC [inline]\fP"

.PP
Definition at line 134 of file server\&.h\&.
.SS "\fBServer\fP& MinecraftServerService::Server::operator<< (const std::string & x)\fC [inline]\fP"

.PP
Definition at line 139 of file server\&.h\&.
.SS "\fBServer\fP& MinecraftServerService::Server::operator<< (\fBStandardEndLine\fP manip)\fC [inline]\fP"

.PP
Definition at line 153 of file server\&.h\&.
.SS "std::istream& MinecraftServerService::Server::operator>> (std::istream & in)\fC [inline]\fP"

.PP
Definition at line 144 of file server\&.h\&.
.SS "void MinecraftServerService::Server::outputListenerThread (int serverPID, int childProcessStdout, struct event_base * base, log4cpp::Category * log, std::vector< \fBListener\fP * > * listeners)\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 162 of file server\&.h\&.
.SS "virtual void MinecraftServerService::Server::reloadServer ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "virtual void MinecraftServerService::Server::restartServer ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "virtual void MinecraftServerService::Server::sendCommand (std::string command)\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "void MinecraftServerService::Server::serverOutputEvent (evutil_socket_t fd, short event, void * arg)\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 170 of file server\&.h\&.
.SS "virtual void MinecraftServerService::Server::serverStatus ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "virtual void MinecraftServerService::Server::startServer ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "virtual void MinecraftServerService::Server::stopServer ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SS "virtual void MinecraftServerService::Server::updateServer ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMinecraftServerService::BukkitServer\fP, \fBMinecraftServerService::GenericServer\fP, \fBMinecraftServerService::SpigotServer\fP, \fBMinecraftServerService::VanillaServer\fP, and \fBMinecraftServerService::BungeeCordServer\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "struct event_base* MinecraftServerService::Server::base = event_base_new()\fC [protected]\fP"

.PP
Definition at line 115 of file server\&.h\&.
.SS "int MinecraftServerService::Server::childProcessGID\fC [protected]\fP"

.PP
Definition at line 111 of file server\&.h\&.
.SS "int MinecraftServerService::Server::childProcessStdin[2]\fC [protected]\fP"

.PP
Definition at line 112 of file server\&.h\&.
.SS "int MinecraftServerService::Server::childProcessStdout[2]\fC [protected]\fP"

.PP
Definition at line 113 of file server\&.h\&.
.SS "int MinecraftServerService::Server::childProcessUID\fC [protected]\fP"

.PP
Definition at line 110 of file server\&.h\&.
.SS "std::vector<\fBListener\fP*>* MinecraftServerService::Server::listeners = new std::vector<\fBListener\fP*>\fC [protected]\fP"

.PP
Definition at line 116 of file server\&.h\&.
.SS "log4cpp::Category* MinecraftServerService::Server::log\fC [protected]\fP"

.PP
Definition at line 114 of file server\&.h\&.
.SS "std::string MinecraftServerService::Server::serverName"

.PP
Definition at line 105 of file server\&.h\&.
.SS "int MinecraftServerService::Server::serverPID = \-1\fC [protected]\fP"

.PP
Definition at line 109 of file server\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
