.TH "MinecraftServerService::Server::ServerOutputEventData" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService::Server::ServerOutputEventData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct event_base * \fBbase\fP"
.br
.ti -1c
.RI "log4cpp::Category * \fBlog\fP"
.br
.ti -1c
.RI "std::vector< \fBListener\fP * > * \fBlisteners\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file server\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct event_base* MinecraftServerService::Server::ServerOutputEventData::base"

.PP
Definition at line 78 of file server\&.h\&.
.SS "std::vector<\fBListener\fP*>* MinecraftServerService::Server::ServerOutputEventData::listeners"

.PP
Definition at line 80 of file server\&.h\&.
.SS "log4cpp::Category* MinecraftServerService::Server::ServerOutputEventData::log"

.PP
Definition at line 79 of file server\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
