.TH "MinecraftServerService::Server::Listener" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService::Server::Listener \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string * \fBcallbackOutput\fP"
.br
.ti -1c
.RI "size_t \fBlines\fP"
.br
.ti -1c
.RI "bool \fBpersistent\fP"
.br
.ti -1c
.RI "size_t \fBcurrentLine\fP"
.br
.ti -1c
.RI "std::string \fBoutput\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file server\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string* MinecraftServerService::Server::Listener::callbackOutput"

.PP
Definition at line 70 of file server\&.h\&.
.SS "size_t MinecraftServerService::Server::Listener::currentLine"

.PP
Definition at line 73 of file server\&.h\&.
.SS "size_t MinecraftServerService::Server::Listener::lines"

.PP
Definition at line 71 of file server\&.h\&.
.SS "std::string MinecraftServerService::Server::Listener::output"

.PP
Definition at line 74 of file server\&.h\&.
.SS "bool MinecraftServerService::Server::Listener::persistent"

.PP
Definition at line 72 of file server\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
