.TH "MinecraftServerService::ServerOutput" 3 "Thu Jun 2 2016" "Version 0.7.4" "Minecraft Server Service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinecraftServerService::ServerOutput \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serverOutput\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::mutex \fBmutex\fP"
.br
.ti -1c
.RI "std::stringstream \fBoutput\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::mutex MinecraftServerService::ServerOutput::mutex"

.SS "std::stringstream MinecraftServerService::ServerOutput::output"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Service from the source code\&.
