.TH "OutputListener" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutputListener \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <outputListener\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutputListener\fP (size_t \fBlinesRequested\fP, std::string \fBlistenerName\fP, bool \fBpersistent\fP, std::function< void(size_t, std::stringstream *, log4cpp::Category *)> \fBcallback\fP)"
.br
.ti -1c
.RI "virtual \fB~OutputListener\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBlistenerName\fP"
.br
.ti -1c
.RI "size_t \fBlinesRequested\fP"
.br
.ti -1c
.RI "size_t \fBcurrentLine\fP = 0"
.br
.ti -1c
.RI "bool \fBpersistent\fP"
.br
.ti -1c
.RI "std::stringstream * \fBlines\fP = new std::stringstream"
.br
.ti -1c
.RI "std::function< void(size_t, std::stringstream *, log4cpp::Category *)> \fBcallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file outputListener\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OutputListener::OutputListener (size_t linesRequested, std::string listenerName, bool persistent, std::function< void(size_t, std::stringstream *, log4cpp::Category *)> callback)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 31 of file outputListener\&.h\&.
.SS "virtual OutputListener::~OutputListener ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 32 of file outputListener\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::function<void(size_t, std::stringstream*, log4cpp::Category*)> OutputListener::callback"

.PP
Definition at line 41 of file outputListener\&.h\&.
.SS "size_t OutputListener::currentLine = 0"

.PP
Definition at line 38 of file outputListener\&.h\&.
.SS "std::stringstream* OutputListener::lines = new std::stringstream"

.PP
Definition at line 40 of file outputListener\&.h\&.
.SS "size_t OutputListener::linesRequested"

.PP
Definition at line 37 of file outputListener\&.h\&.
.SS "std::string OutputListener::listenerName"

.PP
Definition at line 35 of file outputListener\&.h\&.
.SS "bool OutputListener::persistent"

.PP
Definition at line 39 of file outputListener\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
