.TH "Parser" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Json::Value \fBparse\fP (std::string configFile)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBgetFileContents\fP (const char *filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file parser\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string Parser::getFileContents (const char * filename)\fC [protected]\fP"

.PP
Definition at line 48 of file parser\&.cpp\&.
.SS "Json::Value Parser::parse (std::string configFile)"

.PP
Definition at line 32 of file parser\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
