.TH "ServerProcessBuf" 3 "Thu Jun 2 2016" "Version 0.7.4" "Minecraft Server Service" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerProcessBuf \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServerProcessBuf\&.h>\fP
.PP
Inherits streambuf\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerProcessBuf\fP (std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions, std::iostream &sink, std::size_t buff_sz)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ServerProcessBuf::ServerProcessBuf (std::string serverPath, std::string serverJarName, std::string serverAccount, int maxHeapAlloc, int minHeapAlloc, int gcThreadCount, std::vector< std::string > javaArgs, std::vector< std::string > serverOptions, std::iostream & sink, std::size_t buff_sz)\fC [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Service from the source code\&.
