.TH "/home/mel/projects/Misc/Minecraft Server Service/src/setupServers.h" 3 "Fri Jul 1 2016" "Minecraft Server Daemon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mel/projects/Misc/Minecraft Server Service/src/setupServers.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'server\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <json/json\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBMinecraftServerService::Server\fP * > * \fBsetupServers\fP (Json::Value *_config, log4cpp::Category &log)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::vector<\fBMinecraftServerService::Server\fP*>* setupServers (Json::Value * _config, log4cpp::Category & log)"

.PP
Definition at line 35 of file setupServers\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraft Server Daemon from the source code\&.
